language: cpp
os: linux
compiler: gcc
sudo: required
dist: trusty

# Add encrypted API key
env:
  global:
    - secure: BW4/YkeASJvNCwSiyoeIhEbhsmR15Tk2mSlvqqRK/rLnWjb0iQqdfw2apAHkxql96RjTTfzHRIzneWDxTkjh1OComuzG7ik1szak35lW/mfy6SNNYnmi8h98+88+i8RFYtrx47J5qmJ9/v9lRhFG/5yhXbg14b8RN36EdynBVOiNdsYquRzJ7MFzBTzbB9hCtBDgAhsz0wBdTkEFLCEbDsmXIaK74QLDZN6iSgxZz5qlTy4EDv467O+3MVUcGeJlGSeoBUxgHEVslAqpyxqPOAoi0INxH/iIzBvljQNU9XjE8mdsgaL5uOOfdwImYsQYTSwg/LlEDJcXxrgOyQKDHeJK4xrRFAZwy2lF07T5JXh++XSzoGoXl/jSZKejw43+QS2hV8OdD8YTXRyWcU/guoPshabnPBAgAIBt9vubaUNtksqWazqEJNAEG9hHWNAwdu4xMbBM/AxsHj7xP4TZKu89vyoeJ6202iVyTe15yEbOI/AjtNhNGBzmNtc8OZ/ULFHuHrrWgQ2/Mfov0Nv6dItYcEFMSvFaKaGMbWUsQKdER19WxLUvCfsHyhlqyckHJP7m9K0c4NjXMfkds9QqHo/sfmbjCmBKbcLENaMXSH7jKLD07jUsWvdw1gA3ApGQ6T2E9QQHyB1d6F8LrqPQ8MUJWFKseD3pZWrnEObnQVY=

before_install:
  # Add ppa for testing Ubuntu packages
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  # Get the latest versions of the submodules, and push to the remotes (if necessary)
  - chmod +x ./travis_update_submodules.sh
  - ./travis_update_submodules.sh

install:
  - sudo apt-get install -qq g++-5
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-5 90
  - sudo apt-get install -y qt5-default qttools5-dev-tools libqt5svg5*

script:
  # Build the Geometrize app
  - qmake geometrize.pro
  - make

# Tell downstream repositories that the Geometrize app has been updated
after_script:
  - chmod +x trigger_travis.sh
  - ./trigger_travis.sh Tw1ddle geometrize-installer master $TRAVIS_ACCESS_TOKEN_GEOMETRIZE_APP_INSTALLER_TRIGGER
  - ./trigger_travis.sh Tw1ddle geometrize-docs master $TRAVIS_ACCESS_TOKEN_GEOMETRIZE_APP_DOCS_TRIGGER